In [1]:
import pandas as pd

df=pd.read_csv("customer_shopping_behavior.csv")

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Item Purchased          5050 non-null   object
 4   Category                5050 non-null   object
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   object
 7   Size                    4680 non-null   object
 8   Color                   5050 non-null   object
 9   Season                  5050 non-null   object
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   object
 12  Shipping Type           5050 non-null   object
 13  Discount Applied        5050 non-null   object
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   object
 16  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(12)
memory usage: 670.8+ KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4494.000000,4449.000000,4502.000000
mean,2519.570891,44.150495,144.765236,3.668195,25.221901
std,1470.402964,15.282328,275.590101,0.865357,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

In [6]:
df.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,5050.000000,5050.000000,5050,5050,5050,4494.000000,5050,4680,5050,5050,4449.000000,5050,5050,5050,4502.000000,5050,5050
unique,NaN,NaN,3,30,5,NaN,54,4,25,5,NaN,2,6,2,NaN,6,7
top,NaN,NaN,Male,Shirt,Clothing,NaN,New York,M,Black,Spring,NaN,No,Standard,No,NaN,Credit Card,Monthly
freq,NaN,NaN,3018,320,2130,NaN,337,1981,404,1280,NaN,3462,1213,2789,NaN,954,946
mean,2519.570891,44.150495,NaN,NaN,NaN,144.765236,NaN,NaN,NaN,NaN,3.668195,NaN,NaN,NaN,25.221901,NaN,NaN
std,1470.402964,15.282328,NaN,NaN,NaN,275.590101,NaN,NaN,NaN,NaN,0.865357,NaN,NaN,NaN,14.521635,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,10.120000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,0.000000,NaN,NaN
25%,1252.250000,31.000000,NaN,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,13.000000,NaN,NaN
50%,2499.500000,44.000000,NaN,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,25.000000,NaN,NaN
75%,3740.750000,57.000000,NaN,NaN,NaN,89.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,38.000000,NaN,NaN
max,5099.000000,70.000000,NaN,NaN,NaN,1499.760000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
df=df.sort_values(by="Customer ID",ascending=True)
df=df.reset_index(drop = True)

In [9]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [10]:
df["Purchase Amount (USD)"]=df.groupby("Category")["Purchase Amount (USD)"].transform(lambda x:x.fillna(x.median()))
df["Size"]=df["Size"].fillna(df["Size"].mode()[0])
df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x:x.fillna(x.median()))
df["Previous Purchases"]=df.groupby("Category")["Previous Purchases"].transform(lambda x:x.fillna(x.median()))

In [14]:
df.isnull().sum()

Customer_ID               0
Age                       0
Gender                    0
Item_Purchased            0
Category                  0
Purchase_Amount($)        0
Location                  0
Size                      0
Color                     0
Season                    0
Review_Rating             0
Subscription_Status       0
Shipping_Type             0
Discount_Applied          0
Previous_Purchases        0
Payment_Method            0
Frequency_of_Purchases    0
dtype: int64

In [11]:
df.columns=df.columns.str.replace(" ","_")
df=df.rename(columns={"Purchase_Amount_(USD)" : "Purchase_Amount($)"})

In [12]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Item_Purchased', 'Category',
       'Purchase_Amount($)', 'Location', 'Size', 'Color', 'Season',
       'Review_Rating', 'Subscription_Status', 'Shipping_Type',
       'Discount_Applied', 'Previous_Purchases', 'Payment_Method',
       'Frequency_of_Purchases'],
      dtype='object')

In [13]:
df.head()

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount($),Location,Size,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Previous_Purchases,Payment_Method,Frequency_of_Purchases
0,1,55,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14.0,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2.0,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23.0,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49.0,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31.0,PayPal,Annually

In [17]:
# To create Column Age Group

df["Age_Group"]=pd.cut(
    df["Age"],
    bins=[17,30,45,60,70],
    labels=["Young","Adult","Middle Aged","Senior"]
                       )

In [18]:
df[["Age_Group","Age"]].head()

     Age_Group  Age
0  Middle Aged   55
1        Young   19
2  Middle Aged   50
3        Young   21
4        Adult   45

In [19]:
# To create column Loyalty Level

df["Loyalty_Level"]=pd.cut(
    df["Previous_Purchases"],
    bins=[0,10,25,40,50],
    labels=["Bronze","Silver","Gold","Platinum"]
                       )

In [25]:
df[["Loyalty_Level","Previous_Purchases"]].head()

  Loyalty_Level  Previous_Purchases
0        Silver                14.0
1        Bronze                 2.0
2        Silver                23.0
3      Platinum                49.0
4          Gold                31.0

In [24]:
df.head(50)

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount($),Location,Size,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Previous_Purchases,Payment_Method,Frequency_of_Purchases,Age_Grouup,Age_Group,Loyalty_Level
0,1,55,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14.0,Venmo,Fortnightly,Middle Aged,Middle Aged,Silver
1,2,19,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2.0,Cash,Fortnightly,Young,Young,Bronze
2,3,50,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23.0,Credit Card,Weekly,Middle Aged,Middle Aged,Silver
3,4,21,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49.0,PayPal,Weekly,Young,Young,Platinum
4,5,45,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31.0,PayPal,Annually,Adult,Adult,Gold
5,6,46,Male,Sneakers,Footwear,20.0,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14.0,Venmo,Weekly,Middle Aged,Middle Aged,Silver
6,7,63,Male,Shirt,Clothing,85.0,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49.0,Cash,Quarterly,Senior,Senior,Platinum
7,8,27,Male,Shorts,Clothing,34.0,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19.0,Credit Card,Weekly,Young,Young,Silver
8,9,26,Male,Coat,Outerwear,97.0,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8.0,Venmo,Annually,Young,Young,Bronze
9,10,57,Male,Handbag,Accessories,31.0,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4.0,Cash,Quarterly,Middle Aged,Middle Aged,Bronze
10,11,53,Male,Shoes,Footwear,34.0,Arkansas,L,Purple,Fall,4.1,Yes,Store Pickup,Yes,26.0,Bank Transfer,Bi-Weekly,Middle Aged,Middle Aged,Gold
11,12,30,Male,Shorts,Clothing,68.0,Hawaii,S,Olive,Winter,4.9,Yes,Store Pickup,Yes,10.0,Bank Transfer,Fortnightly,Young,Young,Bronze
12,13,61,Male,Coat,Outerwear,72.0,Delaware,M,Gold,Winter,4.5,Yes,Express,Yes,37.0,Venmo,Fortnightly,Senior,Senior,Gold
13,14,65,Male,Dress,Clothing,51.0,New Hampshire,M,Violet,Spring,4.7,Yes,Express,Yes,31.0,PayPal,Weekly,Senior,Senior,Gold
14,15,64,Male,Coat,Outerwear,53.0,New York,L,Teal,Winter,4.7,Yes,Free Shipping,Yes,34.0,Debit Card,Weekly,Senior,Senior,Gold
15,16,64,Male,Skirt,Clothing,81.0,Rhode Island,M,Teal,Winter,2.8,Yes,Store Pickup,Yes,8.0,PayPal,Monthly,Senior,Senior,Bronze
16,17,25,Male,Sunglasses,Accessories,36.0,Alabama,S,Gray,Spring,4.1,Yes,Next Day Air,Yes,44.0,Debit Card,Bi-Weekly,Young,Young,Platinum
17,18,53,Male,Dress,Clothing,38.0,Mississippi,XL,Lavender,Winter,4.7,Yes,2-Day Shipping,Yes,36.0,Venmo,Quarterly,Middle Aged,Middle Aged,Gold
18,19,52,Male,Sweater,Clothing,48.0,Montana,S,Black,Summer,4.6,Yes,Free Shipping,Yes,17.0,Cash,Weekly,Middle Aged,Middle Aged,Silver
19,20,66,Male,Pants,Clothing,90.0,Rhode Island,M,Green,Summer,3.3,Yes,Standard,Yes,46.0,Debit Card,Bi-Weekly,Senior,Senior,Platinum
20,21,21,Male,Pants,Clothing,51.0,Louisiana,M,Black,Winter,2.8,Yes,Express,Yes,50.0,Cash,Every 3 Months,Young,Young,Platinum
21,22,31,Male,Pants,Clothing,62.0,North Carolina,M,Charcoal,Winter,4.1,Yes,Store Pickup,Yes,22.0,Debit Card,Quarterly,Adult,Adult,Silver
22,23,56,Male,Pants,Clothing,37.0,California,M,Peach,Summer,3.2,Yes,Store Pickup,Yes,32.0,Debit Card,Annually,Middle Aged,Middle Aged,Gold
23,24,31,Male,Pants,Clothing,88.0,Oklahoma,XL,White,Winter,4.4,Yes,Express,Yes,40.0,Credit Card,Weekly,Adult,Adult,Gold
24,25,18,Male,Jacket,Outerwear,22.0,Florida,M,Green,Fall,2.9,Yes,Store Pickup,Yes,16.0,Debit Card,Weekly,Young,Young,Silver
25,26,18,Male,Hoodie,Clothing,25.0,Texas,M,Silver,Summer,3.6,Yes,Express,Yes,14.0,PayPal,Annually,Young,Young,Silver
26,27,38,Male,Jewelry,Accessories,20.0,Nevada,M,Red,Spring,3.6,Yes,Next Day Air,Yes,13.0,Credit Card,Annually,Adult,Adult,Silver
27,28,56,Male,Shorts,Clothing,56.0,Kentucky,L,Cyan,Summer,5.0,Yes,Next Day Air,Yes,7.0,Bank Transfer,Every 3 Months,Middle Aged,Middle Aged,Bronze
28,29,54,Male,Handbag,Accessories,94.0,North Carolina,M,Gray,Fall,4.4,Yes,Free Shipping,Yes,41.0,PayPal,Every 3 Months,Middle Aged,Middle Aged,Platinum
29,30,31,Male,Dress,Clothing,48.0,Wyoming,S,Black,Fall,4.1,Yes,Store Pickup,Yes,14.0,Credit Card,Weekly,Adult,Adult,Silver
30,31,57,Male,Jewelry,Accessories,31.0,North Carolina,L,Black,Winter,4.7,Yes,Standard,Yes,16.0,Credit Card,Monthly,Middle Aged,Middle Aged,Silver
31,32,33,Male,Dress,Clothing,79.0,West Virginia,L,Brown,Winter,4.7,Yes,Store Pickup,Yes,45.0,Venmo,Monthly,Adult,Adult,Platinum
32,33,36,Male,Jacket,Outerwear,67.0,Kansas,M,Silver,Summer,4.9,Yes,Free Shipping,Yes,37.0,Venmo,Annually,Adult,Adult,Gold
33,34,54,Male,Pants,Clothing,38.0,Colorado,L,Green,Summer,3.3,Yes,Store Pickup,Yes,45.0,Cash,Quarterly,Middle Aged,Middle Aged,Platinum
34,35,36,Male,T-shirt,Clothing,91.0,North Dakota,L,Violet,Spring,4.6,Yes,2-Day Shipping,Yes,38.0,PayPal,Quarterly,Adult,Adult,Gold
35,36,54,Male,Blouse,Clothing,33.0,Massachusetts,M,Cyan,Summer,4.0,Yes,2-Day Shipping,Yes,48.0,Credit Card,Bi-Weekly,Middle Aged,Middle Aged,Platinum
36,37,35,Male,T-shirt,Clothing,69.0,Illinois,M,Maroon,Winter,4.6,Yes,Free Shipping,Yes,44.0,PayPal,Fortnightly,Adult,Adult,Platinum
37,38,35,Male,Jeans,Clothing,45.0,Indiana,S,Cyan,Summer,2.8,Yes,Store Pickup,Yes,10.0,PayPal,Weekly,Adult,Adult,Bronze
38,39,29,Male,Dress,Clothing,37.0,Florida,M,Red,Winter,3.7,Yes,2-Day Shipping,Yes,44.0,Venmo,Every 3 Months,Young,Young,Platinum
39,40,70,Male,Pants,Clothing,60.0,Arizona,S,Turquoise,Summer,4.2,Yes,Express,Yes,18.0,Credit Card,Monthly,Senior,Senior,Silver
40,41,69,Male,Handbag,Accessories,76.0,Louisiana,L,Beige,Winter,4.6,Yes,Next Day Air,Yes,31.0,Debit Card,Quarterly,Senior,Senior,Gold
41,42,67,Male,Scarf,Accessories,39.0,Alaska,M,Orange,Spring,4.5,Yes,Standard,Yes,40.0,Venmo,Annually,Senior,Senior,Gold
42,43,20,Male,Coat,Outerwear,100.0,Tennessee,M,Beige,Spring,4.1,Yes,Free Shipping,Yes,15.0,PayPal,Annually,Young,Young,Silver
43,44,25,Male,Scarf,Accessories,69.0,Ohio,L,Lavender,Fall,3.7,Yes,Store Pickup,Yes,19.0,PayPal,Fortnightly,Young,Young,Silver
44,45,39,Male,Hat,Accessories,53.0,Kentucky,S,Silver,Summer,4.6,Yes,Free Shipping,Yes,45.0,PayPal,Weekly,Adult,Adult,Platinum
45,46,50,Male,Socks,Clothing,21.0,Tennessee,XL,Indigo,Fall,2.9,Yes,2-Day Shipping,Yes,25.0,PayPal,Annually,Middle Aged,Middle Aged,Silver
46,47,57,Male,Shirt,Clothing,43.0,California,L,White,Summer,2.9,Yes,Store Pickup,Yes,45.0,Cash,Quarterly,Middle Aged,Middle Aged,Platinum
47,48,55,Male,Jewelry,Accessories,54.0,Montana,M,Charcoal,Winter,4.5,Yes,Free Shipping,Yes,36.0,Cash,Weekly,Middle Aged,Middle Aged,Gold
48,49,42,Male,Shirt,Clothing,55.0,Nevada,M,Orange,Summer,2.7,Yes,Store Pickup,Yes,38.0,Cash,Monthly,Adult,Adult,Gold
49,50,68,Male,Hoodie,Clothing,30.0,New Jersey,S,Indigo,Spring,4.6,Yes,Next Day Air,Yes,34.0,Debit Card,Bi-Weekly,Senior,Senior,Gold

In [27]:
df.drop("Age_Grouup",axis=1,inplace=True)

In [30]:
df.to_csv("Customer_Shopping_Behaviour.csv")

TO MYSQL

In [21]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\kavya\.conda\envs\myenv\lib\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in c:\users\kavya\.conda\envs\myenv\lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in c:\users\kavya\.conda\envs\myenv\lib\site-packages (from sqlalchemy) (3.5.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kavya\.conda\envs\myenv\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [28]:
from sqlalchemy import create_engine

#MySQL Connection
username ="root"
password = "1234"
host ="localhost"
port ="3306"
database = "customer_shopping_behaviour"

engine= create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

#Write DataFrame to MySQL
table_name = "customer"   #choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

#Read back sample
pd.read_sql("SELECT * FROM customer LIMIT 5;",engine)

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount($),Location,Size,Color,Season,Review_Rating,Subscription_Status,Shipping_Type,Discount_Applied,Previous_Purchases,Payment_Method,Frequency_of_Purchases,Age_Group,Loyalty_Level
0,1,55,Male,Blouse,Clothing,53.0,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14.0,Venmo,Fortnightly,Middle Aged,Silver
1,2,19,Male,Sweater,Clothing,64.0,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2.0,Cash,Fortnightly,Young,Bronze
2,3,50,Male,Jeans,Clothing,73.0,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23.0,Credit Card,Weekly,Middle Aged,Silver
3,4,21,Male,Sandals,Footwear,90.0,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49.0,PayPal,Weekly,Young,Platinum
4,5,45,Male,Blouse,Clothing,49.0,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31.0,PayPal,Annually,Adult,Gold